name: CI

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "16.13.1"

      - name: Node Version
        run: node -v
      - name: Dependency install
        run: yarn
      - name: Runs linter
        run: yarn lint
