name: Node.js Package

on:
  workflow_dispatch:
    branches: [main]
  push:
    paths:
      - 'package.json'

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org'
      
      - name: Dependencies install
        run: yarn
      
      - name: Runs compiler
        run: yarn build
      
      - name: Runs linter
        run: yarn lint
      
      - name: Tests the code
        run: yarn test
      
      - name: Publish on npm
        run: npm publish --access public

        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
